version: '3.8'

services:
  db:
    image: gvenzl/oracle-free:23
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata

  app:
    build: .
    container_name: ecowatt-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle

volumes:
  oracle-data:
