CREATE TABLE tb_energy_consumption
(
    id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    device            VARCHAR2(100) NOT NULL,
    consumption_watts NUMBER(10, 2) NOT NULL,
    timestamp         TIMESTAMP NOT NULL
);
